version: '2'
services:
  memcached1:
    image: memcached
    ports:
      - "11211:11211"
  memcached2:
    image: memcached
    command: ['-p', '11212']
    ports:
      - "11212:11212"
  memcached3:
    image: memcached
    command: ['-p', '11213', '--enable-ssl', '-o', 'ssl_chain_cert=/app/tests/acceptance/data/localhost.crt,ssl_key=/app/tests/acceptance/data/localhost.key']
    volumes:
      - ./:/app
    ports:
      - "11213:11213"
  memcached_uds:
    image: memcached
    command: ['-s', '/sockets/emcache.sock', '-a', '777']
    volumes:
      - ./:/app
      - type: bind
        source: /tmp/
        target: /sockets/
